# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      # Install packages or any pre-reqs in this phase.
      # Upgrading SAM CLI to latest version
      - python -m pip install --upgrade aws-sam-cli
      - sam --version
      # Installing project dependencies
      - cd infrastructures/ci_cd/src/services/tenant_services/OrderService
      - python -m pip install -r requirements.txt
      - cd ../OrderService
      - python -m pip install -r requirements.txt

  pre_build:
    commands:
      # Run tests, lint scripts or any other pre-build checks.
      - cd ..
      - python -m pip install -r requirements.txt
      - ls -al
      - export PYTHONPATH=./ProductService/
      - cd ../..

      # unit tests needs to be fixed. Commenting for now
      #- python -m pytest tests/unit/ProductService-test_handler.py

  build:
    commands:
      # Use Build phase to build your artifacts (compile, etc.)
      - sam build -t infra/tenant_stacks/tenant_template.yaml

  post_build:
    commands:
      # Use Post-Build for notifications, git tags, upload artifacts to S3
      - sam package --s3-bucket $PACKAGE_BUCKET --output-template-file packaged.yaml

artifacts:
  discard-paths: yes
  files:
    # List of local artifacts that will be passed down the pipeline
    - infrastructures/ci_cd/src/packaged.yaml
